### ISSUE TITLE
MethylDacke extract core dump un Ubuntu 18.04

### ISSUE THREAD

**Issue by tahuh** [dpryan79/MethylDackel#95]
Hi

Currently I'm having trouble with extracting methylated cytosine sites using `MethylDackel extract`

I have aligned reads using bwameth (v0.2.2) and using MethlDackel 0.5.0
The installation was successful with following libraries required (htslib = 1.10.2-51-g0bff7c1)

The command line tested

`MethylDackel extract reference.fa in.bam`

Here reference file is Ensembl GRCh37

The GDB told me it has problem in pileup.c

```
Thread 2 "MethylDackel" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff2332700 (LWP 5507)]
cust_mplp_auto (iter=iter@entry=0x7fffec004f00, _tid=_tid@entry=0x7ffff2331e84, _pos=_pos@entry=0x7ffff2331e88, 
    n_plp=n_plp@entry=0x7ffff2331e94, plp=plp@entry=0x7fffec055fd0) at pileup.c:288
288	        if (iter->pos[i] == iter->min) {
(gdb)
```

Thanks.

**Comment by dpryan79** [comment]
Please try version 0.5.1, which I just released to fix a few memory issues like that. If the bug still shows up then please reopen this.

**Comment by tahuh** [comment]
Hi @dpryan79 

I have tested 0.5.1 but still in the same problem

This is the full backtrace of GDB

```
Thread 2 "MethylDackel" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff263f700 (LWP 29417)]
cust_mplp_auto (iter=iter@entry=0x7fffec004e70, _tid=_tid@entry=0x7ffff263ee84, _pos=_pos@entry=0x7ffff263ee88, n_plp=n_plp@entry=0x7ffff263ee94, plp=plp@entry=0x7fffec056280) at pileup.c:288
288	        if (iter->pos[i] == iter->min) {
(gdb) bt full
#0  cust_mplp_auto (iter=iter@entry=0x7fffec004e70, _tid=_tid@entry=0x7ffff263ee84, _pos=_pos@entry=0x7ffff263ee88, n_plp=n_plp@entry=0x7ffff263ee94, plp=plp@entry=0x7fffec056280) at pileup.c:288
        i = 0
        ret = 0
        new_min = 18446744073709551615
#1  0x000055555555f101 in extractCalls (foo=0x7fffffffde60) at extract.c:391
        config = 0x7fffffffde60
        hdr = 0x7fffec003fc0
        iter = 0x7fffec004e70
        ret = <optimized out>
        tid = 0
        pos = 0
        i = <optimized out>
        seqlen = 1000012
        type = <optimized out>
        rv = <optimized out>
        o = <optimized out>
        bedIdx = 0
        n_plp = 0
        strand = <optimized out>
        direction = <optimized out>
        nmethyl = <optimized out>
        nunmethyl = <optimized out>
        nOff = <optimized out>
        nVariant = <optimized out>
        localBin = 0
        localPos = 0
        localEnd = 1000001
        localTid = 0
        localPos2 = 0
        lastPos = 0
        nVariantPositions = 0
        plp = 0x7fffec056280
        seq = 0x7ffff1d4a010 'N' <repeats 200 times>...
        base = 65 'A'
        context = "HG"
        tnc = <optimized out>
        data = 0x7fffec056250
        lastCpG = 0x0
        lastCHG = 0x0
        os = 0x7fffec000b60
        os_CpG = 0x7fffec000b80
        os_CHG = 0x7fffec000ba0
        os_CHH = 0x7fffec000bc0
---Type <return> to continue, or q <return> to quit---
        fai = 0x7fffec001db0
        bai = 0x7fffec0050a0
        fp = 0x7fffec013a70
        __PRETTY_FUNCTION__ = "extractCalls"
#2  0x00007ffff7c29669 in start_thread (arg=<optimized out>) at pthread_create.c:479
        ret = <optimized out>
        pd = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140737260025600, -269718404055552016, 140737488346494, 140737488346495, 140737488346496, 140737260023744, 269688545975873520, 269700372400975856}, 
              mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = 0
#3  0x00007ffff7614323 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
No locals.

```

If you have pre-compiled binary of stable version, can you let me know?

Thanks.
